version: '3.9'
services:
  api:
    build: ./api_server_node
    ports: ["4000:4000"]
    environment:
      - PORT=4000
      - ADMIN_PIN=${ADMIN_PIN:-1234}
      - BUSINESS_NAME=${BUSINESS_NAME:-Sharma Tiffin Service}
      - UPI_ID=${UPI_ID:-prince190992-1@okicici}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - RAZORPAY_WEBHOOK_SECRET=${RAZORPAY_WEBHOOK_SECRET}
    volumes:
      - api_data:/app/data
volumes:
  api_data: {}
